# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpu < Formula
  desc "GPU.ai command-line interface — provision and manage GPU instances from your terminal."
  homepage "https://gpu.ai"
  version "1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.3/gpu_1.3_darwin_amd64.tar.gz"
      sha256 "b96ddc4f6549f5157ee169ab65e2b9741b01c4523934b1169f8a5cdd5ce96f07"

      define_method(:install) do
        bin.install "gpu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.3/gpu_1.3_darwin_arm64.tar.gz"
      sha256 "1ba0dda11755e10ffd874fe000a87397bafa171760420191809fafd016773785"

      define_method(:install) do
        bin.install "gpu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.3/gpu_1.3_linux_amd64.tar.gz"
      sha256 "be4cd876f170215207af57cf6ebace13a1a3798eb7fd2a6c43675005e03ed852"
      define_method(:install) do
        bin.install "gpu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.3/gpu_1.3_linux_arm64.tar.gz"
      sha256 "52a24eb0a518261daf8dbb2490ec0cbb6d6e8106c41bfcd1c9fb6c072cea7451"
      define_method(:install) do
        bin.install "gpu"
      end
    end
  end

  test do
    system "#{bin}/gpu", "--version"
  end
end
