# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpu < Formula
  desc "GPU.ai command-line interface — provision and manage GPU instances from your terminal."
  homepage "https://gpu.ai"
  version "1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.1/gpu_1.1_darwin_amd64.tar.gz"
      sha256 "329f1f57b3bb68e2156a7196563aab7c087cb81b88a79c61fe246442e07484a5"

      define_method(:install) do
        bin.install "gpu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.1/gpu_1.1_darwin_arm64.tar.gz"
      sha256 "7aebc44a7bdd5abdc11e0809fe6e6019d1de86a876a2feac227a188a1ec1527f"

      define_method(:install) do
        bin.install "gpu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.1/gpu_1.1_linux_amd64.tar.gz"
      sha256 "b6b49a2d477818e5550bfd83f4a9981e0fca88abab6127d2af9fae22f01b3043"
      define_method(:install) do
        bin.install "gpu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gpuai-dev/gpu-cli/releases/download/v1.1/gpu_1.1_linux_arm64.tar.gz"
      sha256 "bdc2e55db04b0ce06a0f2b2403d9677ab2770b7bca895097eb136a4346760e5d"
      define_method(:install) do
        bin.install "gpu"
      end
    end
  end

  test do
    system "#{bin}/gpu", "--version"
  end
end
